# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: xeroxIRC
description: >- # this means to ignore newlines until "baseurl:"
  The official xeroxIRC website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
timezone: UTC
permalink: /posts/:year-:month-:day_:title
server_map: https://www.google.com/maps/d/u/0/embed?mid=1Z19gVD9VICsw5tPp7EtJUA0OTFyUnL8z&ll=30.983999006823808%2C-77.4755849375&z=2
swi_baseurl: https://gb.xeroxirc.net

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

sass:
    style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
